package com.example.projekt.model.Enums;

public enum Rank {
    PRIVATE,
    PRIVATE_FIRST_CLASS,
    SPECIALIST,
    CORPORAL,
    SERGEANT,
    STAFF_SERGEANT,
    SERGEANT_FIRST_CLASS,
    MASTER_SERGEANT,
    FIRST_SERGEANT,
    SERGEANT_MAJOR,
    COMMAND_SERGEANT_MAJOR,
    SERGEANT_MAJOR_OF_THE_ARMY,
    WARRANT_OFFICER,
    CHIEF_WARRANT_OFFICER_2,
    CHIEF_WARRANT_OFFICER_3,
    CHIEF_WARRANT_OFFICER_4,
    CHIEF_WARRANT_OFFICER_5,
    SECOND_LIEUTENANT,
    FIRST_LIEUTENANT,
    CAPTAIN,
    MAJOR,
    LIEUTENANT_COLONEL,
    COLONEL,
    BRIGADIER_GENERAL,
    MAJOR_GENERAL,
    LIEUTENANT_GENERAL,
    GENERAL,
    GENERAL_OF_THE_ARMY
}

